# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/til',
                'doc_host': 'https://audreyfeldroy.github.io',
                'git_url': 'https://github.com/audreyfeldroy/til',
                'lib_path': 'til'},
  'syms': {'til.core': {'til.core.foo': ('core.html#foo', 'til/core.py')}}}
