# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/til',
                'doc_host': 'https://audreyfeldroy.github.io',
                'git_url': 'https://github.com/audreyfeldroy/til',
                'lib_path': 'til'},
  'syms': { 'til.core': { 'til.core.HelloSayer': ('core.html#hellosayer', 'til/core.py'),
                          'til.core.HelloSayer.__init__': ('core.html#hellosayer.__init__', 'til/core.py'),
                          'til.core.HelloSayer.say': ('core.html#hellosayer.say', 'til/core.py'),
                          'til.core.foo': ('core.html#foo', 'til/core.py'),
                          'til.core.say_hello': ('core.html#say_hello', 'til/core.py')}}}
