name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os:  [ubuntu]
        version: ["3.10"]
    steps: 
      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: ${{ matrix.version }}
          pre: 1

